---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: voiceagent-api-deployment
    labels:
        app: voiceagent-api
spec:
  selector:
    matchLabels:
      app: voiceagent-api
  replicas: 1
  template:
    metadata:
      labels:
        app: voiceagent-api
    spec:
      containers:
        - name: voiceagent-api
          image: <REGISTRY>/<NAMESPACE>/voiceagent-api:latest
          imagePullPolicy: Always
          ports:
              - containerPort: 8080
          envFrom:
          - secretRef:
              name: voiceagentapi-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: voiceagent-api-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 31001
  selector:
    app: voiceagent-api
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: restart-voiceagent-deployment
  namespace: default
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: restart-voiceagent-deployment
  namespace: default
spec:
  concurrencyPolicy: Forbid # Do not run concurrently!
  schedule: '0 */2 * * *'     # Run every 2 hours
  jobTemplate:
    spec:
      backoffLimit: 2 
      activeDeadlineSeconds: 600 
      template:
        spec:
          serviceAccountName: restart-voiceagent-deployment # Run under the service account created above
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl # Specify the kubectl image
              command: # The kubectl command to execute
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment/voiceagent-api-deployment'
